main:
  # required
  host: "0.0.0.0"
  # required
  port: 3000
  # required
  kws: "hellohello"

asr:
  # optional
  provider: "本地"

llm:
  # optional
  provider: "百炼"
  # optional
  enable_thinking: false
  model: qwen-max-latest

tts:
  # optional
  provider: "本地"
  # optional
  spk_id: "chelsie"
  # optional
  volume: 10
